development:
  adapter: postgresql
  database: ILearn_development
  encoding: utf8
  host: localhost
  port: 5432
  username: linuxlite
  password: 123456
test:
  adapter: postgresql
  database: ILearn_test
  encoding: utf8
  host: localhost
  port: 5432
  username: linuxlite
  password: 123456